<a href="https://colab.research.google.com/github/LUBNAAZEEM/Data-Jobs-Dashboard/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [11]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [12]:
%%sql
select
 orderdate,
 quantity * netprice * exchangerate as net_revenue

from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

In [17]:
%%sql
select
 orderdate,
 count(distinct customerkey) as Total_Customers

from sales

where orderdate between '2023,1,1' and '2023,12,31'

group by
orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers
0    2023-01-01               12
1    2023-01-02               49
2    2023-01-03               64
3    2023-01-04               78
4    2023-01-05               87
..          ...              ...
359  2023-12-27               73
360  2023-12-28               75
361  2023-12-29               55
362  2023-12-30               91
363  2023-12-31                9

[364 rows x 2 columns]

In [21]:
%%sql
SELECT orderdate, COUNT(*) AS total_customers
FROM sales
GROUP BY orderdate
ORDER BY orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3294 rows affected.

       orderdate  total_customers
0     2015-01-01               25
1     2015-01-02                8
2     2015-01-03               21
3     2015-01-05               10
4     2015-01-06               12
...          ...              ...
3289  2024-04-16               32
3290  2024-04-17               61
3291  2024-04-18               57
3292  2024-04-19               50
3293  2024-04-20               97

[3294 rows x 2 columns]

In [23]:
%%sql

SELECT DISTINCT
 Continent

from
customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [33]:
%%sql

SELECT
s.orderdate,
COUNT(distinct s.customerkey) AS total_customers,
COUNT(distinct case when c.continent = 'Europe' then s.customerkey end) AS eu_customers,
COUNT(distinct case when c.continent = 'North America' then s.customerkey end) as na_customers,
COUNT(distinct case when c.continent = 'Australia' then s.customerkey end) as au_customers

FROM
sales s

left join customer c on s.customerkey = c.customerkey

where
s.orderdate between '2023,01,01' and '2023,12,31'

group by
s.orderdate


ORDER BY
s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  au_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

In [45]:
%%sql

SELECT
p.categoryname,

SUM ( case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as net_revenue_2022,
SUM ( case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as net_revenue_2023


FROM
sales s
left join product p on s.productkey = p.productkey


group by
p.categoryname


ORDER BY
p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  net_revenue_2022  net_revenue_2023
0                          Audio         766938.21         688690.18
1        Cameras and camcorders         2382532.56        1983546.29
2                    Cell phones        8119665.07        6002147.63
3                      Computers       17862213.49       11650867.21
4                 Games and Toys         316127.30         270374.96
5                Home Appliances        6612446.68        5919992.87
6  Music, Movies and Audio Books        2989297.28        2180768.13
7                   TV and Video        5815336.61        4412178.23

In [50]:
%%sql

SELECT
p.categoryname,

AVG( case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as avg_revenue_2022,
AVG( case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as avg_revenue_2023,

MIN( case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as min_revenue_2022,
MIN( case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as min_revenue_2023,


MAX( case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as max_revenue_2022,
MAX( case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate  end ) as max_revenue_2023


FROM
sales s
left join product p on s.productkey = p.productkey


group by
p.categoryname


ORDER BY
p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_revenue_2022,avg_revenue_2023,min_revenue_2022,min_revenue_2023,max_revenue_2022,max_revenue_2023
0,Audio,392.30,425.38,9.31,10.85,3473.36,2730.87
1,Cameras and camcorders,1210.02,1210.96,6.74,5.98,15008.39,13572.00
2,Cell phones,722.20,623.28,2.53,2.28,7692.37,8912.22
3,Computers,1565.62,1292.39,0.83,0.75,38082.66,27611.60
4,Games and Toys,81.29,80.83,2.83,3.49,5202.01,3357.30
5,Home Appliances,1755.36,1886.55,4.04,4.54,31654.55,32915.59
6,"Music, Movies and Audio Books",386.61,334.58,7.29,6.91,5415.19,3804.91
7,TV and Video,1535.61,1687.90,41.30,42.30,30259.41,27503.12

In [62]:
%%sql

select

PERCENTILE_CONT(.50) within group (order by netprice) as  median_net_price

from
 sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_net_price
0            191.95

In [71]:
%%sql

SELECT
p.categoryname as category,

PERCENTILE_CONT(0.50) within group (order by
      (case when s.orderdate between '2022-01-01' and '2022-01-31' then s.quantity * s.netprice * s.exchangerate
      end)) as  median_sales_2022,
PERCENTILE_CONT(0.50) within group (order by
      (case when s.orderdate between '2023-01-01' and '2023-01-31' then s.quantity * s.netprice * s.exchangerate
      end)) as  median_sales_2023


FROM
sales s
left join product p on s.productkey = p.productkey


group by
p.categoryname


ORDER BY
p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  median_sales_2022  median_sales_2023
0                          Audio             208.80             235.94
1        Cameras and camcorders              698.48             843.00
2                    Cell phones             507.02             363.17
3                      Computers             935.71             706.69
4                 Games and Toys              29.89              31.24
5                Home Appliances             814.45             877.50
6  Music, Movies and Audio Books             208.36             166.02
7                   TV and Video             664.90             916.23